apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: {{ .Values.mongoservice.name }}
spec:
  ports:
  - port: {{ .Values.mongoservice.port }}
    protocol: TCP
    targetPort: {{ .Values.mongoservice.targetPort }}
  selector:
    app: mongo
  type: ClusterIP
status:
  loadBalancer: {}
