apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
      name: nodeapp
    spec:
      containers:
      - image: {{ .Values.node.image }}:{{ .Values.node.tag }}
        imagePullPolicy: IfNotPresent
        name: nodeapp
        ports:
        - containerPort: 4000
          protocol: TCP
