apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodeapp
  name: nodeapp
spec:
  replicas: {{ .Values.node.replicas }}
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
      name: nodeapp
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of mongodb"; while ! nc -z {{ .Values.mongoservice.name }} 27017; do sleep 1; printf "-"; done; echo -e "  >> Mongodb is up";']
      containers:
      - image: {{ .Values.node.image }}:{{ .Values.node.tag }}
        imagePullPolicy: IfNotPresent
        name: nodeapp
        ports:
        - containerPort: 4000
          protocol: TCP
